### ISSUE TITLE
(Optionally) add a previous/next button on set view page

### ISSUE THREAD

**Issue by caro401** [flyingcatband/tunebook#30]
To make it easy for bands whose folders are in performance/setlist order to move between sets in order. This doesn't make sense for everyone though, so it should be a configuration option to `ViewSet` if possible

**Comment by jarhodes314** [comment]
`ViewSet` probably doesn't know enough to just determine what page to link to, so it should probably have optional props for next/previous set URLs and only show each button when the relevant URL exists.
